version: 2.1

jobs:
  build-and-test:
    docker:
      - image: denoland/deno:1.20.6
    steps:
      - checkout
      - run: |
          deno test --allow-net --allow-env

workflows:
  sample:
    jobs:
      - build-and-test